# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks: # general hooks
    -   id: check-ast
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-toml
    -   id: check-xml
    -   id: check-yaml
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: name-tests-test
    -   id: trailing-whitespace
    -   id: check-added-large-files
        exclude: doc/

-   repo: https://github.com/econchick/interrogate
    rev: 1.5.0
    hooks:
    -   id: interrogate
        exclude: '^doc/|^\.venv/|'
        args: [--fail-under=80, -vv]
        additional_dependencies: [setuptools]
-   repo: https://github.com/kynan/nbstripout
    rev: 0.7.1
    hooks:
    -   id: nbstripout

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.1
    hooks:
        # Linter
    -   id: ruff
        args: [--fix]
        # Formatter
    -   id: ruff-format
