name: Example Issues
description: Example Issue
title: "[Good First Issue]: "
labels: ["good first issue"]
assignees:
  - cameron-currie
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "Sample text!"
    validations:
      required: true
  - type: dropdown
    id: example-drop-down
    attributes:
      label: Where did you encounter the problem?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: example-checkbox
    attributes:
      label: Example checkbox
      description: By submitting this issue, you have created an example [issue](https://example.com)
      options:
        - label: I have created an issue
          required: true
