name: Techincal Problem
description: You have encountered a bug or technical problem that has raised an error or produced an unexpected output.
title: "[Bug]: "
labels: ["bug"]
assignees:
  - cameron-currie
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      value: "Tell us what you see"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output or error message. This will be automatically formatted into code, so no need for backticks.
      render: shell
